import Modal from "@/components/Modal";
import "./globals.css";

export const metadata = {
  title: "Trello 2.0",
  description: "Generated by Mohammadjavad Salehi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="https://trello.com/assets/8d4bcc6f7600ccbb6675.svg" />
      </head>
      <body className="bg-secondary">
        {children}
        <Modal></Modal>
      </body>
    </html>
  );
}